apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-aws-credentials
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | quote }}
